// <auto-generated />
namespace ONTAP_Finaly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201912221626523_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
